[2022-12-20T14:20:31.681+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: co2balance.CleanData manual__2022-12-20T14:20:29.187472+00:00 [queued]>
[2022-12-20T14:20:31.692+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: co2balance.CleanData manual__2022-12-20T14:20:29.187472+00:00 [queued]>
[2022-12-20T14:20:31.692+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-20T14:20:31.692+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-20T14:20:31.692+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-20T14:20:31.708+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): CleanData> on 2022-12-20 14:20:29.187472+00:00
[2022-12-20T14:20:31.715+0000] {standard_task_runner.py:55} INFO - Started process 281 to run task
[2022-12-20T14:20:31.719+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'co2balance', 'CleanData', 'manual__2022-12-20T14:20:29.187472+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/co2balance.py', '--cfg-path', '/tmp/tmpxshc2v78']
[2022-12-20T14:20:31.721+0000] {standard_task_runner.py:83} INFO - Job 17: Subtask CleanData
[2022-12-20T14:20:31.848+0000] {task_command.py:389} INFO - Running <TaskInstance: co2balance.CleanData manual__2022-12-20T14:20:29.187472+00:00 [running]> on host 1a27c7ed0719
[2022-12-20T14:20:31.985+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=CO2balance
AIRFLOW_CTX_DAG_ID=co2balance
AIRFLOW_CTX_TASK_ID=CleanData
AIRFLOW_CTX_EXECUTION_DATE=2022-12-20T14:20:29.187472+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-20T14:20:29.187472+00:00
[2022-12-20T14:20:32.580+0000] {clean_project_file.py:15} INFO - Data read from excel file completed successfully
[2022-12-20T14:20:32.585+0000] {clean_project_file.py:52} INFO - Read headers from excel file completed successfully
[2022-12-20T14:20:32.586+0000] {clean_project_file.py:86} INFO - Renamed headers from excel file completed successfully
[2022-12-20T14:20:32.958+0000] {clean_project_file.py:105} INFO - Data cleaned into dataframe successfully
[2022-12-20T14:20:32.959+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/app/populate/cook_stove/clean_project_file.py", line 106, in clean_project_file
    projects.to_excel('../data/project_data.xlsx', index=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2291, in to_excel
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/excel.py", line 835, in write
    writer, engine=engine, storage_options=storage_options
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_openpyxl.py", line 57, in __init__
    engine_kwargs=engine_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 926, in __init__
    path, mode, storage_options=storage_options, is_text=False
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 711, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '../data/project_data.xlsx'
[2022-12-20T14:20:32.974+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=co2balance, task_id=CleanData, execution_date=20221220T142029, start_date=20221220T142031, end_date=20221220T142032
[2022-12-20T14:20:32.987+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 17 for task CleanData ([Errno 2] No such file or directory: '../data/project_data.xlsx'; 281)
[2022-12-20T14:20:33.014+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-20T14:20:33.038+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
